name: Deploy to Server

on:
  push:
    branches:
      - deploy  # This will trigger the workflow when code is pushed to the deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r project/requirements.txt
          
      - name: Minify JavaScript
        run: |
          npm install -g terser
          terser static/js/*.js -o static/js/*.min.js  # Adjust path based on where your JS is

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} user@your-server-ip 'bash -s' < deploy.sh
